title = "Reid Mitchell"
baseURL = "https://reidmit.com/"
languageCode = "en-us"

disableHugoGeneratorInject = true
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ["taxonomyTerm"]

[taxonomies]
tag = "tags"

[params]
author = "Reid Mitchell"
description = "Software engineer, designer, and filmmaker based in San Francisco."
